app = "guess-the-drop"
primary_region = "sea" # us-west

[env]
  SERVER_PROTOCOL = "https"
  SERVER_DOMAIN = "guessthedrop.com"
  SERVER_PORT = 8080
  SERVER_HOST_URI = "https://guessthedrop.com"
  DB_DATABASE = "guess-the-drop"
  R2_BUCKET = "guess-the-drop"
  R2_BUCKET_PUBLIC_URL = "https://r2.guessthedrop.com"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  max_machines_running = 3
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

